# Generated by Django 5.2.16 on 2026-07-21 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_post_author'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='nmae',
            new_name='name',
        ),
    ]
